// Owners: Nikolay Karlov, Grigorenko Paul
// This code is generated by a template, so don't modify it.
// All changes will be discarded.
// Last generated: 09/11/2019 20:11:27
// CacheTags.cs

namespace DemoWebApplication.Templates
{
	using System.Linq;
    using QA.DotNetCore.Caching.Interfaces;
    using QA.DotNetCore.Engine.Persistent.Interfaces.Settings;

    /// <summary>
    /// Контентные версионные теги
    /// </summary>
	public static partial class CacheTags
	{
		/// <summary>
        /// AbstractItem
        /// Элемент структуры сайта
		/// </summary>
        public static QPContent QPAbstractItem = new QPContent { Id = 537, SiteId = 52, Name = "AbstractItem", NetName = "QPAbstractItem"};
		/// <summary>
        /// ItemDefinition
        /// Типы страниц и виджетов
		/// </summary>
        public static QPContent QPDiscriminator = new QPContent { Id = 538, SiteId = 52, Name = "ItemDefinition", NetName = "QPDiscriminator"};
		/// <summary>
        /// Маркетинговые регионы
        /// 
		/// </summary>
        public static QPContent MarketingRegion = new QPContent { Id = 539, SiteId = 52, Name = "Маркетинговые регионы", NetName = "MarketingRegion"};
		/// <summary>
        /// Локализация
        /// 
		/// </summary>
        public static QPContent QPCulture = new QPContent { Id = 540, SiteId = 52, Name = "Локализация", NetName = "QPCulture"};
		/// <summary>
        /// ItemTitleFormat
        /// Шаблон для заголовка страницы. Например, &quot;ООН [[region]] [[title]]&quot;.
		/// </summary>
        public static QPContent ItemTitleFormat = new QPContent { Id = 541, SiteId = 52, Name = "ItemTitleFormat", NetName = "ItemTitleFormat"};
		/// <summary>
        /// AbtractItemRegion
        /// Представление для региона. Получает данные из MarketRegion
		/// </summary>
        public static QPContent QPRegion = new QPContent { Id = 542, SiteId = 52, Name = "AbtractItemRegion", NetName = "QPRegion"};
		/// <summary>
        /// TrailedAbstractItem
        /// 
		/// </summary>
        public static QPContent TrailedAbstractItem = new QPContent { Id = 545, SiteId = 52, Name = "TrailedAbstractItem", NetName = "TrailedAbstractItem"};
		/// <summary>
        /// SiteSettings
        /// Настройки сайта
		/// </summary>
        public static QPContent SiteSetting = new QPContent { Id = 578, SiteId = 52, Name = "SiteSettings", NetName = "SiteSetting"};
		/// <summary>
        /// Region Tag
        /// 
		/// </summary>
        public static QPContent QpRegionTag = new QPContent { Id = 602, SiteId = 52, Name = "Region Tag", NetName = "QpRegionTag"};
		/// <summary>
        /// Region Tag Values
        /// 
		/// </summary>
        public static QPContent QpRegionTagValue = new QPContent { Id = 603, SiteId = 52, Name = "Region Tag Values", NetName = "QpRegionTagValue"};
		/// <summary>
        /// ItemDefinitionConstraint
        /// 
		/// </summary>
        public static QPContent QPItemDefinitionConstraint = new QPContent { Id = 10609, SiteId = 52, Name = "ItemDefinitionConstraint", NetName = "QPItemDefinitionConstraint"};
		/// <summary>
        /// Новости
        /// Контент новостей
		/// </summary>
        public static QPContent News = new QPContent { Id = 10610, SiteId = 52, Name = "Новости", NetName = "News"};
		/// <summary>
        /// Новости Группы новостей
        /// 
		/// </summary>
        public static QPContent NewsGroup = new QPContent { Id = 10612, SiteId = 52, Name = "Новости Группы новостей", NetName = "NewsGroup"};
		/// <summary>
        /// СМИ
        /// 
		/// </summary>
        public static QPContent QpSMI = new QPContent { Id = 10624, SiteId = 52, Name = "СМИ", NetName = "QpSMI"};
		/// <summary>
        /// Рубрики Новостей
        /// 
		/// </summary>
        public static QPContent QpNewsRubric = new QPContent { Id = 10627, SiteId = 52, Name = "Рубрики Новостей", NetName = "QpNewsRubric"};
		/// <summary>
        /// Популярные услуги
        /// Виджет на главной
		/// </summary>
        public static QPContent PopularServicesValue = new QPContent { Id = 10644, SiteId = 52, Name = "Популярные услуги", NetName = "PopularServicesValue"};
		/// <summary>
        /// Секции на главной
        /// 
		/// </summary>
        public static QPContent MainSectionsValue = new QPContent { Id = 10646, SiteId = 52, Name = "Секции на главной", NetName = "MainSectionsValue"};
		/// <summary>
        /// Акции
        /// 
		/// </summary>
        public static QPContent QpAction = new QPContent { Id = 10648, SiteId = 52, Name = "Акции", NetName = "QpAction"};
		/// <summary>
        /// Блог
        /// 
		/// </summary>
        public static QPContent QpBlog = new QPContent { Id = 10651, SiteId = 52, Name = "Блог", NetName = "QpBlog"};
		/// <summary>
        /// AB тесты
        /// Контент для регистрации AB-тестов
		/// </summary>
        public static QPContent AbTest = new QPContent { Id = 10663, SiteId = 52, Name = "AB тесты", NetName = "AbTest"};
		/// <summary>
        /// Контейнер AB тестирования
        /// 
		/// </summary>
        public static QPContent AbTestBaseContainer = new QPContent { Id = 10664, SiteId = 52, Name = "Контейнер AB тестирования", NetName = "AbTestBaseContainer"};
		/// <summary>
        /// Скрипт AB тестирования
        /// 
		/// </summary>
        public static QPContent AbTestScript = new QPContent { Id = 10665, SiteId = 52, Name = "Скрипт AB тестирования", NetName = "AbTestScript"};
		/// <summary>
        /// Контейнер скриптов
        /// 
		/// </summary>
        public static QPContent AbTestScriptContainer = new QPContent { Id = 10666, SiteId = 52, Name = "Контейнер скриптов", NetName = "AbTestScriptContainer"};
		/// <summary>
        /// Контейнер клиентских редиректов
        /// 
		/// </summary>
        public static QPContent AbTestClientRedirectContainer = new QPContent { Id = 10667, SiteId = 52, Name = "Контейнер клиентских редиректов", NetName = "AbTestClientRedirectContainer"};
		/// <summary>
        /// Клиентский редирект AB тестирования
        /// 
		/// </summary>
        public static QPContent AbTestClientRedirect = new QPContent { Id = 10668, SiteId = 52, Name = "Клиентский редирект AB тестирования", NetName = "AbTestClientRedirect"};
	}

	/// <summary>
	/// Утилиты для работы с кештегами
	/// </summary>
	public class CacheTagUtilities
	{
		readonly IQpContentCacheTagNamingProvider _qpContentCacheTagNamingProvider;
		readonly QpSettings _qpSettings;

		public CacheTagUtilities(IQpContentCacheTagNamingProvider qpContentCacheTagNamingProvider, QpSettings qpSettings)
		{
			_qpContentCacheTagNamingProvider = qpContentCacheTagNamingProvider;
			_qpSettings = qpSettings;
		}

		/// <summary>
		/// Преобразование тегов в массив
		/// </summary>
		public string[] Merge(params QPContent[] tags)
		{
			return tags.Select(c => _qpContentCacheTagNamingProvider.Get(c.Name, c.SiteId, _qpSettings.IsStage)).Where(t => t != null).ToArray();
		}
	}
	
    public class QPContent
    {
        public int Id { get; set; }
        public int SiteId { get; set; }
        public string Name { get; set; }
		public string NetName { get; set; }
    }
}
