// sidebar
export const TOGGLE_OPEN_STATE = 'TOGGLE_OPEN_STATE';
export const TOGGLE_LEFT_POSITION = 'TOGGLE_LEFT_POSITION';
export const TOGGLE_RIGHT_POSITION = 'TOGGLE_RIGHT_POSITION';
export const TOGGLE_ALL_ZONES = 'TOGGLE_ALL_ZONES';

// tree
export const TOGGLE_COMPONENT = 'TOGGLE_COMPONENT';
export const TOGGLE_SUBTREE = 'TOGGLE_SUBTREE';
export const LOADED_COMPONENT_TREE = 'LOADED_COMPONENT_TREE';


// edit widget
export const EDIT_WIDGET_ACTIONS = {
  EDIT_WIDGET: 'EDIT_WIDGET',
  GET_ABSTRACT_ITEM_INFO_REQUESTED: 'ABSTRACT_ITEM_INFO_REQUESTED',
  GET_ABSTRACT_ITEM_INFO_SUCCESS: 'GET_ABSTRACT_ITEM_INFO_SUCCESS',
  GET_ABSTRACT_ITEM_INFO_FAIL: 'GET_ABSTRACT_ITEM_INFO_FAIL',
  SHOW_QP_FORM: 'EDIT_WIDGET_SHOW_QP_FORM',
  CLOSE_QP_FORM: 'EDIT_WIDGET_CLOSE_QP_FORM',
  SAVED_QP_FORM: 'EDIT_WIDGET_SAVED_QP_FORM',
  NEED_RELOAD: 'EDIT_WIDGET_NEED_RELOAD',
};

