// sidebar
export const TOGGLE_OPEN_STATE = 'TOGGLE_OPEN_STATE';
export const TOGGLE_LEFT_POSITION = 'TOGGLE_LEFT_POSITION';
export const TOGGLE_RIGHT_POSITION = 'TOGGLE_RIGHT_POSITION';
export const TOGGLE_ALL_ZONES = 'TOGGLE_ALL_ZONES';

// tabs
export const TOGGLE_TAB = 'TOGGLE_TAB';

// tree
export const TOGGLE_COMPONENT = 'TOGGLE_COMPONENT';
export const TOGGLE_SUBTREE = 'TOGGLE_SUBTREE';
export const TOGGLE_FULL_SUBTREE = 'TOGGLE_FULL_SUBTREE';
export const LOADED_COMPONENT_TREE = 'LOADED_COMPONENT_TREE';


// edit widget
export const EDIT_WIDGET_ACTIONS = {
  EDIT_WIDGET: 'EDIT_WIDGET',
  SHOW_QP_FORM: 'EDIT_WIDGET_SHOW_QP_FORM',
};

export const ADD_WIDGET_ACTIONS = {
  ADD_WIDGET_TO_ZONE: 'ADD_WIDGET_TO_ZONE',
  SHOW_AVAILABLE_WIDGETS: 'SHOW_AVAILABLE_WIDGETS',
  HIDE_AVAILABLE_WIDGETS: 'HIDE_AVAILABLE_WIDGETS',
  SELECT_WIDGET_TO_ADD: 'SELECT_WIDGET_TO_ADD',

};

export const QP_FORM_ACTIONS = {
  NEED_RELOAD: 'QP_FORM_NEED_RELOAD',
  CLOSE_QP_FORM: 'QP_FORM_CLOSE',
};

export const CONTENT_META_INFO_ACTION = {
  GET_ABSTRACT_ITEM_INFO_REQUESTED: 'ABSTRACT_ITEM_INFO_REQUESTED',
  GET_ABSTRACT_ITEM_INFO_SUCCESS: 'GET_ABSTRACT_ITEM_INFO_SUCCESS',
  GET_ABSTRACT_ITEM_INFO_FAIL: 'GET_ABSTRACT_ITEM_INFO_FAIL',
  GET_AVAILABLE_WIDGETS_REQUESTED: 'GET_AVAILABLE_WIDGETS_REQUESTED',
  GET_AVAILABLE_WIDGETS_SUCCESS: 'GET_AVAILABLE_WIDGETS_SUCCESS',
  GET_AVAILABLE_WIDGETS_FAIL: 'GET_AVAILABLE_WIDGETS_FAIL',
};
