// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using Quantumart.QP8.EntityFrameworkCore;
namespace QA.DemoSite.DAL
{
    public partial class AbTestClientRedirect: IQPArticle
    {
        public AbTestClientRedirect()
        {
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

		private String _VersionNumber;
		public virtual String VersionNumber 
		{ 
			get { return _VersionNumber; }
			set { _VersionNumber = QpDataContext.Current.ReplacePlaceholders(value);}
		}
		private String _RedirectUrl;
		public virtual String RedirectUrl 
		{ 
			get { return _RedirectUrl; }
			set { _RedirectUrl = QpDataContext.Current.ReplacePlaceholders(value);}
		}
		/// <summary>
		/// 
		/// </summary>			
		public virtual AbTestClientRedirectContainer Container { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public virtual Int32? Container_ID { get; set; }
	}
}
	
