// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using Quantumart.QP8.EntityFrameworkCore;
namespace QA.DemoSite.DAL
{
    public partial class AbTest: IQPArticle
    {
        public AbTest()
        {
		    ABTestContainers = new HashSet<AbTestBaseContainer>();
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

		private String _Title;
		public virtual String Title 
		{ 
			get { return _Title; }
			set { _Title = QpDataContext.Current.ReplacePlaceholders(value);}
		}
        public virtual Boolean? Enabled { get; set; }
		private String _Percentage;
		public virtual String Percentage 
		{ 
			get { return _Percentage; }
			set { _Percentage = QpDataContext.Current.ReplacePlaceholders(value);}
		}
        public virtual DateTime? StartDate { get; set; }
        public virtual DateTime? EndDate { get; set; }
		private String _Comment;
		public virtual String Comment 
		{ 
			get { return _Comment; }
			set { _Comment = QpDataContext.Current.ReplacePlaceholders(value);}
		}
		/// <summary>
		/// 
		/// </summary>
		public  ICollection<AbTestBaseContainer> ABTestContainers { get; set; }
	}
}
	
