// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
using Quantumart.QP8.EntityFrameworkCore;
namespace QA.DemoSite.DAL
{
    public partial class BlogPost: IQPArticle
    {
        public BlogPost()
        {
		    Tags = new HashSet<BlogPost2BlogTagForTags>();
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

		private String _Title;
		public virtual String Title 
		{ 
			get { return _Title; }
			set { _Title = QpDataContext.Current.ReplacePlaceholders(value);}
		}
		private String _Brief;
		public virtual String Brief 
		{ 
			get { return _Brief; }
			set { _Brief = QpDataContext.Current.ReplacePlaceholders(value);}
		}
        public virtual DateTime? PostDate { get; set; }
		private String _Text;
		public virtual String Text 
		{ 
			get { return _Text; }
			set { _Text = QpDataContext.Current.ReplacePlaceholders(value);}
		}
        public virtual String Image { get; set; }
		private String _YoutubeVideoCode;
		public virtual String YoutubeVideoCode 
		{ 
			get { return _YoutubeVideoCode; }
			set { _YoutubeVideoCode = QpDataContext.Current.ReplacePlaceholders(value);}
		}
		/// <summary>
		/// 
		/// </summary>			
		public virtual BlogCategory Category { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public virtual Int32? Category_ID { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public  ICollection<BlogPost2BlogTagForTags> Tags { get; set; }
	}
}
	
