// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
namespace QA.DemoSite.DAL
{
    public partial class BlogTag: IQPArticle
    {
        public BlogTag()
        {
		    BackwardForTags = new HashSet<BlogPost>();
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

        public virtual String Title { get; set; }
		/// <summary>
		/// Auto-generated backing property for 68571/Tags
		/// </summary>
		public  ICollection<BlogPost> BackwardForTags { get; set; }
	}
}
	
