// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
namespace QA.DemoSite.DAL
{
    public partial class NewsCategory: IQPArticle
    {
        public NewsCategory()
        {
		    NewsByCategory = new HashSet<NewsItem>();
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

        public virtual String Title { get; set; }
		/// <summary>
		/// Auto-generated backing property for field (id: 68544)/Category NewsByCategory
		/// </summary>
		public  ICollection<NewsItem> NewsByCategory { get; set; }
	}
}
