// Code generated by a template
using System;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.SqlClient;

namespace QA.DemoSite.DAL
{
    public class QpDataContextConnectionScope
    {

    }
}
