// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
namespace Demo.DAL
{
    public partial class ItemTitleFormat: IQPArticle
    {
        public ItemTitleFormat()
        {
		    Item = new HashSet<QPAbstractItem>();
		    News = new HashSet<News>();
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

        public virtual String Value { get; set; }
        public virtual String Description { get; set; }
		/// <summary>
		/// Auto-generated backing property for field (id: 27532)/TitleFormat Item
		/// </summary>
		public  ICollection<QPAbstractItem> Item { get; set; }
		/// <summary>
		/// Auto-generated backing property for field (id: 47992)/TitleFormat News
		/// </summary>
		public  ICollection<News> News { get; set; }
	}
}
	
