// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
namespace Demo.DAL
{
    public partial class MainSectionsValue: IQPArticle
    {
        public MainSectionsValue()
        {
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

        public virtual String Title { get; set; }
        public virtual Int32? Order { get; set; }
        public virtual String LT1Text { get; set; }
        public virtual String LT1URL { get; set; }
        public virtual String LB2Text { get; set; }
        public virtual String LB2URL { get; set; }
        public virtual String RT3Text { get; set; }
        public virtual String RT3URL { get; set; }
        public virtual String RB4Text { get; set; }
        public virtual String RB4URL { get; set; }
		#region Generated Content properties
        // public Int32 OrderExact { get { return this.Order == null ? default(Int32) : this.Order.Value; } }
		#endregion
	}
}
	
