// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
namespace Demo.DAL
{
    public partial class MarketingRegion: IQPArticle
    {
        public MarketingRegion()
        {
		    Children = new HashSet<MarketingRegion>();
		    BackwardForRegions = new HashSet<QpRegionTagValue>();
		    BackwardForRegions1 = new HashSet<News>();
		    BackwardForRegions2 = new HashSet<QpAction>();
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

        public virtual String Title { get; set; }
        public virtual String Url { get; set; }
		/// <summary>
		/// 
		/// </summary>			
		public virtual MarketingRegion Parent { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public virtual Int32? Parent_ID { get; set; }
		/// <summary>
		/// Auto-generated backing property for field (id: 27523)/Parent Children
		/// </summary>
		public  ICollection<MarketingRegion> Children { get; set; }
		/// <summary>
		/// Auto-generated backing property for 37889/Regions
		/// </summary>
		public  ICollection<QpRegionTagValue> BackwardForRegions { get; set; }
		/// <summary>
		/// Auto-generated backing property for 47923/Regions
		/// </summary>
		public  ICollection<News> BackwardForRegions1 { get; set; }
		/// <summary>
		/// Auto-generated backing property for 48119/Regions
		/// </summary>
		public  ICollection<QpAction> BackwardForRegions2 { get; set; }
	}
}
	
