// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
namespace Demo.DAL
{
    public partial class QpAction: IQPArticle
    {
        public QpAction()
        {
		    Regions = new HashSet<MarketingRegion>();
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

        public virtual String Title { get; set; }
        public virtual String Alias { get; set; }
        public virtual String Description { get; set; }
        public virtual String Text { get; set; }
        public virtual DateTime? ShowUntil { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public  ICollection<MarketingRegion> Regions { get; set; }
	}
}
	
