// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
namespace Demo.DAL
{
    public partial class QPDiscriminator: IQPArticle
    {
        public QPDiscriminator()
        {
		    AllowedItemDefinitions1 = new HashSet<QPDiscriminator>();
		    AllowedItemDefinitions = new HashSet<QPItemDefinitionConstraint>();
		    Items = new HashSet<QPAbstractItem>();
		    AllowDefinition = new HashSet<QPItemDefinitionConstraint>();
		    BackwardForAllowedItemDefinitions1 = new HashSet<QPDiscriminator>();
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

        public virtual String Title { get; set; }
        public virtual String Name { get; set; }
        public virtual Int32? PreferredContentId { get; set; }
        public virtual String CategoryName { get; set; }
        public virtual String Description { get; set; }
        public virtual String IconUrl { get; set; }
        public virtual Boolean? IsPage { get; set; }
        public virtual String AllowedZones { get; set; }
        public virtual Boolean? FilterPartByUrl { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public  ICollection<QPDiscriminator> AllowedItemDefinitions1 { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public  ICollection<QPItemDefinitionConstraint> AllowedItemDefinitions { get; set; }
		/// <summary>
		/// Auto-generated backing property for field (id: 27516)/Discriminator Items
		/// </summary>
		public  ICollection<QPAbstractItem> Items { get; set; }
		/// <summary>
		/// Auto-generated backing property for field (id: 47908)/Target AllowDefinition
		/// </summary>
		public  ICollection<QPItemDefinitionConstraint> AllowDefinition { get; set; }
		/// <summary>
		/// Auto-generated backing property for 27552/AllowedItemDefinitions1
		/// </summary>
		public  ICollection<QPDiscriminator> BackwardForAllowedItemDefinitions1 { get; set; }
		#region Generated Content properties
        // public string IconUrlUrl { get; set; }
        // public string IconUrlUploadPath { get; set; }
        // public Int32 PreferredContentIdExact { get { return this.PreferredContentId == null ? default(Int32) : this.PreferredContentId.Value; } }
        // public Boolean IsPageExact { get { return this.IsPage == null ? default(Boolean) : this.IsPage.Value; } }
        // public Boolean FilterPartByUrlExact { get { return this.FilterPartByUrl == null ? default(Boolean) : this.FilterPartByUrl.Value; } }
		#endregion
	}
}
	
