// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
namespace Demo.DAL
{
    public partial class QpNewsRubric: IQPArticle
    {
        public QpNewsRubric()
        {
		    BackwardForRubrics = new HashSet<News>();
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

        public virtual String Title { get; set; }
        public virtual Int32? RubricId { get; set; }
        public virtual Int32? Order { get; set; }
        public virtual String Alias { get; set; }
		/// <summary>
		/// Auto-generated backing property for 47990/Rubrics
		/// </summary>
		public  ICollection<News> BackwardForRubrics { get; set; }
		#region Generated Content properties
        // public Int32 RubricIdExact { get { return this.RubricId == null ? default(Int32) : this.RubricId.Value; } }
        // public Int32 OrderExact { get { return this.Order == null ? default(Int32) : this.Order.Value; } }
		#endregion
	}
}
	
