// Code generated by a template
using System;
using System.Linq;
using System.Collections;
using System.Collections.Generic;
namespace Demo.DAL
{
    public partial class QpRegionTagValue: IQPArticle
    {
        public QpRegionTagValue()
        {
		    Regions = new HashSet<MarketingRegion>();
        }

        public virtual Int32 Id { get; set; }
        public virtual Int32 StatusTypeId { get; set; }
        public virtual bool Visible { get; set; }
        public virtual bool Archive { get; set; }
        public virtual DateTime Created { get; set; }
        public virtual DateTime Modified { get; set; }
        public virtual Int32 LastModifiedBy { get; set; }
        public virtual StatusType StatusType { get; set; }

        public virtual String Value { get; set; }
		/// <summary>
		/// 
		/// </summary>			
		public virtual QpRegionTag Parent { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public virtual Int32? Parent_ID { get; set; }
		/// <summary>
		/// 
		/// </summary>
		public  ICollection<MarketingRegion> Regions { get; set; }
	}
}
	
